/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

import controllers.controllerIniciarSesion;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JButton;
import utilities.OSValidator;

/**
 *
 * @author Gleycer
 */
public class viewVerificarSesion extends javax.swing.JDialog {
    private OSValidator validarOS;

    /**
     * Creates new form viewVerificarSesion
     */
    public viewVerificarSesion(java.awt.Frame parent, boolean modal, ModalityType modalityType) {
        super(parent,modal);
        this.validarOS = new OSValidator();
        validarOS.validarOS();
         this.setUndecorated(true);
        initComponents();
        this.setTitle("Verificar Sesión");
        this.setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/logo principal.png"));
        this.setIconImage(icon);
        inicializarEventos();
    }

    private void inicializarEventos() {
    controllerIniciarSesion controller = new controllerIniciarSesion(this);
    btnVerificarSesion.addActionListener(controller);
                                      }

    public JButton getBtnVerificarSesion() {
        return btnVerificarSesion;
    }



    public String getTxtContraseña() {
        return txtContraseña.getText();
    }

    public String getTxtUsuario() {
        return txtUsuario.getText();
    }

    public void setTxtUsuario(String Usuario) {
        txtUsuario.setText(Usuario);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnVerificarSesion = new javax.swing.JButton();
        btnReestablecerCampos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 136, 249), 2));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Verificar Sesión");
        jLabel1.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0, 0, 8));

        jLabel2.setText("Usuario:");
        jPanel3.add(jLabel2);

        txtUsuario.setEditable(false);
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel3.add(txtUsuario);

        jLabel3.setText("Contraseña:");
        jPanel3.add(jLabel3);

        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyTyped(evt);
            }
        });
        jPanel3.add(txtContraseña);

        jLabel4.setText("Por favor verifique sesión para continuar:");

        btnVerificarSesion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnVerificarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/seleccionar_p.png"))); // NOI18N
        btnVerificarSesion.setText("Iniciar Sesión");
        btnVerificarSesion.setToolTipText("Seleccionar");
        btnVerificarSesion.setAlignmentY(0.0F);
        btnVerificarSesion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnVerificarSesion.setContentAreaFilled(false);
        btnVerificarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerificarSesion.setIconTextGap(0);
        btnVerificarSesion.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnVerificarSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/seleccionar_g.png"))); // NOI18N
        btnVerificarSesion.setVerifyInputWhenFocusTarget(false);
        btnVerificarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerificarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarSesionActionPerformed(evt);
            }
        });

        btnReestablecerCampos.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnReestablecerCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/reestablecer_p.png"))); // NOI18N
        btnReestablecerCampos.setText("Reestablecer Campos");
        btnReestablecerCampos.setToolTipText("Agregar Nuevo");
        btnReestablecerCampos.setAlignmentY(0.0F);
        btnReestablecerCampos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnReestablecerCampos.setContentAreaFilled(false);
        btnReestablecerCampos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReestablecerCampos.setIconTextGap(0);
        btnReestablecerCampos.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnReestablecerCampos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/reestablecer_g.png"))); // NOI18N
        btnReestablecerCampos.setVerifyInputWhenFocusTarget(false);
        btnReestablecerCampos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReestablecerCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReestablecerCamposActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/header_verificar_sesion.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerificarSesion)
                .addGap(18, 18, 18)
                .addComponent(btnReestablecerCampos)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerificarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReestablecerCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        char c = evt.getKeyChar();
        if(txtUsuario.getText().length()>=15) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyTyped
        char c = evt.getKeyChar();
        if(txtContraseña.getText().length()>=15) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtContraseñaKeyTyped

    private void btnVerificarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarSesionActionPerformed

    }//GEN-LAST:event_btnVerificarSesionActionPerformed

    private void btnReestablecerCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReestablecerCamposActionPerformed
reestablecerCampos();      

    }//GEN-LAST:event_btnReestablecerCamposActionPerformed

    private void reestablecerCampos() {
    txtUsuario.setText("");
    txtContraseña.setText("");
                                      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewVerificarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewVerificarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewVerificarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewVerificarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewVerificarSesion(new javax.swing.JFrame(), true, Dialog.ModalityType.APPLICATION_MODAL).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReestablecerCampos;
    private javax.swing.JButton btnVerificarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
