/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

import controllers.controllerCerrarSesion;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import utilities.CalcularInactividad;
import utilities.OSValidator;

/**
 *
 * @author Gleycer
 */
public class viewPrincipal extends javax.swing.JFrame {
    private OSValidator validarOS;
    private String usuario;
    private controllerCerrarSesion controllerCerrarSesion;

    /**
     * Creates new form viewPrincipal
     */
    public viewPrincipal() {
        this.validarOS = new OSValidator();
        validarOS.validarOS();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/logo principal.png"));
        this.setIconImage(icon);       
        this.setTitle("Menú Principal");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        CalcularInactividad calcularInactividad = new CalcularInactividad();
        calcularInactividad.setView(this);
        calcularInactividad.obtenerEventos();
        calcularInactividad.calcularInactividad();
    }

    public JMenu getMenuTopUser() {
        return menuTopUser;
    }

    public JButton getBtnPrincipalConfiguraciones() {
        return btnPrincipalConfiguraciones;
    }

    public JButton getBtnPrincipalUsuarios() {
        return btnPrincipalUsuarios;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        btnPrincipalUsuarios = new javax.swing.JButton();
        btnPrincipalConfiguraciones = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuTopUser = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Zona Educativa Yaracuy");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel9.setLayout(flowLayout1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/header.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel1);

        jPanel7.add(jPanel9);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/fichapersonal_p.png"))); // NOI18N
        jButton8.setToolTipText("Registrar Ficha Personal");
        jButton8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setIconTextGap(10);
        jButton8.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jButton8.setPreferredSize(new java.awt.Dimension(80, 60));
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/fichapersonal_g.png"))); // NOI18N
        jButton8.setVerifyInputWhenFocusTarget(false);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton8);

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/consultar_p.png"))); // NOI18N
        jButton10.setToolTipText("Consultar Datos de Personal");
        jButton10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setFocusPainted(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setIconTextGap(10);
        jButton10.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jButton10.setPreferredSize(new java.awt.Dimension(80, 60));
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/consultar_g.png"))); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton10);

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/tramites_p.png"))); // NOI18N
        jButton14.setToolTipText("Trámites Administrativos");
        jButton14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setFocusPainted(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setIconTextGap(10);
        jButton14.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jButton14.setPreferredSize(new java.awt.Dimension(80, 60));
        jButton14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/tramites_g.png"))); // NOI18N
        jButton14.setVerifyInputWhenFocusTarget(false);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14);

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/evaluaciones_p.png"))); // NOI18N
        jButton13.setToolTipText("Evaluaciones");
        jButton13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setFocusPainted(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setIconTextGap(10);
        jButton13.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jButton13.setPreferredSize(new java.awt.Dimension(80, 60));
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/evaluaciones_g.png"))); // NOI18N
        jButton13.setVerifyInputWhenFocusTarget(false);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13);

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/historial_tramite_p.png"))); // NOI18N
        jButton16.setToolTipText("Historial de Trámites Administrativos");
        jButton16.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setFocusPainted(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setIconTextGap(10);
        jButton16.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jButton16.setPreferredSize(new java.awt.Dimension(80, 60));
        jButton16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/historial_tramite_g.png"))); // NOI18N
        jButton16.setVerifyInputWhenFocusTarget(false);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton16);

        btnPrincipalUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnPrincipalUsuarios.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        btnPrincipalUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/usuarios_p.png"))); // NOI18N
        btnPrincipalUsuarios.setToolTipText("Gestionar Usuarios");
        btnPrincipalUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnPrincipalUsuarios.setBorderPainted(false);
        btnPrincipalUsuarios.setContentAreaFilled(false);
        btnPrincipalUsuarios.setFocusPainted(false);
        btnPrincipalUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrincipalUsuarios.setIconTextGap(10);
        btnPrincipalUsuarios.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnPrincipalUsuarios.setPreferredSize(new java.awt.Dimension(80, 60));
        btnPrincipalUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/usuarios_g.png"))); // NOI18N
        btnPrincipalUsuarios.setVerifyInputWhenFocusTarget(false);
        btnPrincipalUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrincipalUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalUsuariosActionPerformed(evt);
            }
        });
        jPanel8.add(btnPrincipalUsuarios);

        btnPrincipalConfiguraciones.setBackground(new java.awt.Color(255, 255, 255));
        btnPrincipalConfiguraciones.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        btnPrincipalConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/configuraciones_p.png"))); // NOI18N
        btnPrincipalConfiguraciones.setToolTipText("Configuraciones");
        btnPrincipalConfiguraciones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnPrincipalConfiguraciones.setBorderPainted(false);
        btnPrincipalConfiguraciones.setContentAreaFilled(false);
        btnPrincipalConfiguraciones.setFocusPainted(false);
        btnPrincipalConfiguraciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrincipalConfiguraciones.setIconTextGap(10);
        btnPrincipalConfiguraciones.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnPrincipalConfiguraciones.setPreferredSize(new java.awt.Dimension(80, 60));
        btnPrincipalConfiguraciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/configuraciones_g.png"))); // NOI18N
        btnPrincipalConfiguraciones.setVerifyInputWhenFocusTarget(false);
        btnPrincipalConfiguraciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrincipalConfiguraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalConfiguracionesActionPerformed(evt);
            }
        });
        jPanel8.add(btnPrincipalConfiguraciones);

        jButton15.setBackground(new java.awt.Color(255, 255, 255));
        jButton15.setFont(new java.awt.Font("Aharoni", 0, 11)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/cerrar_p.png"))); // NOI18N
        jButton15.setToolTipText("Cerrar Sesión");
        jButton15.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setFocusPainted(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setIconTextGap(10);
        jButton15.setMargin(new java.awt.Insets(10, 14, 10, 14));
        jButton15.setPreferredSize(new java.awt.Dimension(80, 60));
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_menu/cerrar_g.png"))); // NOI18N
        jButton15.setVerifyInputWhenFocusTarget(false);
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton15);

        jPanel7.add(jPanel8);

        jPanel1.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, -50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo principal.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel2);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        jMenuBar2.add(jMenu1);

        menuTopUser.setText("Usuario:");
        jMenuBar2.add(menuTopUser);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {       
            new viewFichaPersonal(this,true,Dialog.ModalityType.DOCUMENT_MODAL).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(viewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       new viewConsultarDatosPersonal(this,true).setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnPrincipalUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalUsuariosActionPerformed
       new viewCatalagoUsuarios(this,true,Dialog.ModalityType.DOCUMENT_MODAL).setVisible(true);
    }//GEN-LAST:event_btnPrincipalUsuariosActionPerformed

    private void btnPrincipalConfiguracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalConfiguracionesActionPerformed
      new viewBackup(this,true,Dialog.ModalityType.DOCUMENT_MODAL).setVisible(true);
    }//GEN-LAST:event_btnPrincipalConfiguracionesActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        new viewEvaluacionObrero(this,true,Dialog.ModalityType.DOCUMENT_MODAL).setVisible(true);
        //
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            new viewTramitesAdministrativos(this,true,Dialog.ModalityType.DOCUMENT_MODAL).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(viewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
       int seleccion = JOptionPane.showOptionDialog(
            null,
            "¿Está seguro de que desea salir? Se cerrará la aplicación si acepta.",
            "Salir",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,    // null para icono por defecto.
            null,   // null para YES, NO y CANCEL
            null);

        if (seleccion != -1)
        if(seleccion + 1 == 1) {
            controllerCerrarSesion = new controllerCerrarSesion(this);
            controllerCerrarSesion.cerrarSesion(usuario);
            this.dispose();
           try {
               new viewInicio().setVisible(true);
           } catch (IOException ex) {
               Logger.getLogger(viewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
            new viewHistorialTramites(this,true,Dialog.ModalityType.DOCUMENT_MODAL).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(viewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     int seleccion = JOptionPane.showOptionDialog(
            null,
            "¿Está seguro de que desea salir? Se cerrará la aplicación si acepta.",
            "Salir",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,    // null para icono por defecto.
            null,   // null para YES, NO y CANCEL
            null);

        if (seleccion != -1)
            
        if(seleccion == 0) {
            controllerCerrarSesion = new controllerCerrarSesion(this);
            controllerCerrarSesion.cerrarSesion(usuario);
            this.dispose();
        }
        else {
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
             }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
}catch(Exception e){
  e.printStackTrace();
}//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrincipalConfiguraciones;
    private javax.swing.JButton btnPrincipalUsuarios;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JMenu menuTopUser;
    // End of variables declaration//GEN-END:variables
}
