/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;


import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import controllers.controllerConsultarTramite;
import controllers.controllerDatosPersonales;
import controllers.controllerListarHistorialTramites;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import utilities.OSValidator;
import utilities.tablaModel;

/**
 *
 * @author Gleycer
 */
public class viewHistorialTramites extends javax.swing.JDialog {
    private OSValidator validarOS;
    private int id_direccion = 0;
    private controllerListarHistorialTramites c;
    

    /**
     * Creates new form viewConsultarDatosPersonal
     */
    public viewHistorialTramites(java.awt.Frame parent, boolean modal,ModalityType modalityType) throws SQLException {
        super(parent,modal);
        this.validarOS = new OSValidator();
        validarOS.validarOS();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setPreferredSize(screenSize);
        initComponents();

        this.setTitle("Historial de Trámites Administrativos");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/logo principal.png"));
        this.setLocationRelativeTo(null);
        cargarTableHistorial();
        autoCompletado();
        inicializarEventos();
                                        }
    
    public void inicializarEventos() {
    controllerConsultarTramite controller = new controllerConsultarTramite(this);
    btnConsultar.addActionListener(controller);
    btnSeleccionar.addActionListener(controller);
                                                            }
    
    public void reestablecerTable() {
    tableHistorialTramites.setModel(new DefaultTableModel());
                                    }
    
        private void autoCompletado() {
        
 TextAutoCompleter textAutoCompleter = null;

textAutoCompleter = new TextAutoCompleter(txtDatos, new AutoCompleterCallback() {

@Override

public void callback(Object selectedItem) {
}

});
    textAutoCompleter.setMode(0);
       List ListItem = null;
        try {
            ListItem = controllerDatosPersonales.CargarPersonal();
        } catch (SQLException ex) {
            Logger.getLogger(viewTramitesAdministrativos.class.getName()).log(Level.SEVERE, null, ex);
        }
     
              int i;
        
    if (ListItem != null) {
    int size = ListItem.size();
    for (i=0;i<size;i++)        {
     textAutoCompleter.addItem(ListItem.get(i));
                                }
                     }
                          }
        
        public void cargarTableHistorial() {
        c= new controllerListarHistorialTramites(this);
        tablaModel tablaModel = new tablaModel();
        c.controllerListarHistorialTramites(tablaModel);
        tableHistorialTramites.setModel(tablaModel);
                                      }

    public JTable getTableHistorialTramites() {
        return tableHistorialTramites;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public void setBtnAgregar(JButton btnAgregar) {
        this.btnAgregar = btnAgregar;
    }

    public JButton getBtnSeleccionar() {
        return btnSeleccionar;
    }

    public void setBtnSeleccionar(JButton btnSeleccionar) {
        this.btnSeleccionar = btnSeleccionar;
    }

    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public JButton getBtnListadoPersonal() {
        return btnListadoPersonal;
    }

    public JComboBox getComboTipoBusqueda() {
        return comboTipoBusqueda;
    }

    public String getTxtDatos() {
        return txtDatos.getText();
    }

    public JTextField getDatos() {
        return txtDatos;
    }

    public void setTxtDatos(String Datos) {
        txtDatos.setText(Datos);
    }
    
    


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBtnFijoInt = new javax.swing.ButtonGroup();
        groupBtnTurno = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton("Consultar");
        btnListadoPersonal = new javax.swing.JButton("Consultar");
        jLabel84 = new javax.swing.JLabel();
        txtDatos = new javax.swing.JTextField();
        comboTipoBusqueda = new javax.swing.JComboBox();
        btnConsultar1 = new javax.swing.JButton("Consultar");
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDesde = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtHasta = new com.toedter.calendar.JDateChooser();
        comboEstatus = new javax.swing.JComboBox();
        comboEstatus1 = new javax.swing.JComboBox();
        comboTipoTramite = new javax.swing.JComboBox();
        btnConsultar2 = new javax.swing.JButton("Consultar");
        btnConsultar3 = new javax.swing.JButton("Consultar");
        btnConsultar4 = new javax.swing.JButton("Consultar");
        btnConsultar5 = new javax.swing.JButton("Consultar");
        btnConsultar6 = new javax.swing.JButton("Consultar");
        jPanel12 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistorialTramites = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnCambiarStatus = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));
        jPanel13.add(jLabel3);

        jPanel3.add(jPanel13, java.awt.BorderLayout.LINE_START);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel9.setLayout(flowLayout1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/header.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel1);

        jPanel10.add(jPanel9);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Historial de Trámites Administrativos");

        btnConsultar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Prueba/paste_64px_opt.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setToolTipText("Consultar Datos de Personal");
        btnConsultar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar.setIconTextGap(5);
        btnConsultar.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnConsultar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Prueba/paste_64px_opt(1).png"))); // NOI18N
        btnConsultar.setVerifyInputWhenFocusTarget(false);
        btnConsultar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnListadoPersonal.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnListadoPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/listado_p.png"))); // NOI18N
        btnListadoPersonal.setText("Ver Listado de Personal");
        btnListadoPersonal.setToolTipText("Consultar Datos de Personal");
        btnListadoPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnListadoPersonal.setContentAreaFilled(false);
        btnListadoPersonal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListadoPersonal.setIconTextGap(5);
        btnListadoPersonal.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnListadoPersonal.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/listado_g.png"))); // NOI18N
        btnListadoPersonal.setVerifyInputWhenFocusTarget(false);
        btnListadoPersonal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnListadoPersonal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListadoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoPersonalActionPerformed(evt);
            }
        });

        jLabel84.setText("Introduzca Datos:");

        txtDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtDatos.setEnabled(false);
        txtDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatosActionPerformed(evt);
            }
        });
        txtDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatosKeyTyped(evt);
            }
        });

        comboTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..", "Buscar por Cédula", "Buscar por Nombre" }));
        comboTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoBusquedaActionPerformed(evt);
            }
        });

        btnConsultar1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/seleccionarCargo_p.png"))); // NOI18N
        btnConsultar1.setText("Herramientas de Búsqueda");
        btnConsultar1.setToolTipText("Consultar Datos de Personal");
        btnConsultar1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnConsultar1.setContentAreaFilled(false);
        btnConsultar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar1.setIconTextGap(5);
        btnConsultar1.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnConsultar1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/seleccionarCargo_g.png"))); // NOI18N
        btnConsultar1.setVerifyInputWhenFocusTarget(false);
        btnConsultar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar1ActionPerformed(evt);
            }
        });

        jPanel4.setVisible(false);

        jLabel4.setText("Desde:");

        txtDesde.setPreferredSize(new java.awt.Dimension(93, 20));

        jLabel5.setText("Hasta:");

        txtHasta.setPreferredSize(new java.awt.Dimension(93, 20));

        comboEstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Estatus...", "Pendiente", "Procesado", "Obrero" }));
        comboEstatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboEstatusFocusLost(evt);
            }
        });

        comboEstatus1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Tipo de Personal...", "Docente", "Administrativo", "Obrero" }));
        comboEstatus1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboEstatus1FocusLost(evt);
            }
        });

        comboTipoTramite.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..", "Ingreso", "Reactivación", "Traslado", "Ascenso", "Clasificación", "Liberación de Cargo", "Suspensión", "Modificación de Horas", "Egresos", "Modificación de Cargo", "Modificación de Datos Personales" }));
        comboTipoTramite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTipoTramiteItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboTipoTramite, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(comboEstatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboEstatus1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboEstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboTipoTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnConsultar2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnConsultar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/reestablecer_p.png"))); // NOI18N
        btnConsultar2.setText("Fecha");
        btnConsultar2.setToolTipText("Consultar Datos de Personal");
        btnConsultar2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnConsultar2.setContentAreaFilled(false);
        btnConsultar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar2.setIconTextGap(5);
        btnConsultar2.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnConsultar2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/reestablecer_g.png"))); // NOI18N
        btnConsultar2.setVerifyInputWhenFocusTarget(false);
        btnConsultar2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar2ActionPerformed(evt);
            }
        });

        btnConsultar3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnConsultar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/seleccionar_p.png"))); // NOI18N
        btnConsultar3.setText("Tipo de Personal");
        btnConsultar3.setToolTipText("Consultar Datos de Personal");
        btnConsultar3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnConsultar3.setContentAreaFilled(false);
        btnConsultar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar3.setIconTextGap(5);
        btnConsultar3.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnConsultar3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/seleccionar_g.png"))); // NOI18N
        btnConsultar3.setVerifyInputWhenFocusTarget(false);
        btnConsultar3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar3ActionPerformed(evt);
            }
        });

        btnConsultar4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnConsultar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/agregar2_p.png"))); // NOI18N
        btnConsultar4.setText("Tipo de Trámite");
        btnConsultar4.setToolTipText("Consultar Datos de Personal");
        btnConsultar4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnConsultar4.setContentAreaFilled(false);
        btnConsultar4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar4.setIconTextGap(5);
        btnConsultar4.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnConsultar4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/agregar2_g.png"))); // NOI18N
        btnConsultar4.setVerifyInputWhenFocusTarget(false);
        btnConsultar4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar4ActionPerformed(evt);
            }
        });

        btnConsultar5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnConsultar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/generar_p.png"))); // NOI18N
        btnConsultar5.setText("Estatus");
        btnConsultar5.setToolTipText("Consultar Datos de Personal");
        btnConsultar5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnConsultar5.setContentAreaFilled(false);
        btnConsultar5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar5.setIconTextGap(5);
        btnConsultar5.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnConsultar5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/generar_g.png"))); // NOI18N
        btnConsultar5.setVerifyInputWhenFocusTarget(false);
        btnConsultar5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar5ActionPerformed(evt);
            }
        });

        btnConsultar6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnConsultar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Prueba/paste_64px_opt.png"))); // NOI18N
        btnConsultar6.setText("Consultar");
        btnConsultar6.setToolTipText("Consultar Datos de Personal");
        btnConsultar6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnConsultar6.setContentAreaFilled(false);
        btnConsultar6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar6.setIconTextGap(5);
        btnConsultar6.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnConsultar6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Prueba/paste_64px_opt(1).png"))); // NOI18N
        btnConsultar6.setVerifyInputWhenFocusTarget(false);
        btnConsultar6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnConsultar6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnConsultar6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnConsultar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultar4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultar5)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultar2)
                    .addComponent(btnConsultar3)
                    .addComponent(btnConsultar4)
                    .addComponent(btnConsultar5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(638, 638, 638))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel84)
                                .addGap(9, 9, 9)
                                .addComponent(txtDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnListadoPersonal)))
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar1)
                        .addGap(263, 263, 263))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListadoPersonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel84)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.add(jPanel8);

        jPanel3.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableHistorialTramites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableHistorialTramites);

        btnSeleccionar.setFont(new java.awt.Font("Aharoni", 1, 11)); // NOI18N
        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/seleccionar_p.png"))); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setToolTipText("Seleccionar");
        btnSeleccionar.setAlignmentY(0.0F);
        btnSeleccionar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSeleccionar.setContentAreaFilled(false);
        btnSeleccionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSeleccionar.setIconTextGap(0);
        btnSeleccionar.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnSeleccionar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/seleccionar_g.png"))); // NOI18N
        btnSeleccionar.setVerifyInputWhenFocusTarget(false);
        btnSeleccionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Aharoni", 1, 11)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/agregar_p.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("Agregar Nuevo");
        btnAgregar.setAlignmentY(0.0F);
        btnAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setIconTextGap(0);
        btnAgregar.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnAgregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/agregar_g.png"))); // NOI18N
        btnAgregar.setVerifyInputWhenFocusTarget(false);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCambiarStatus.setFont(new java.awt.Font("Aharoni", 1, 11)); // NOI18N
        btnCambiarStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/reestablecer_p.png"))); // NOI18N
        btnCambiarStatus.setText("<html><center>Cambiar<br> Estatus</center></html>");
        btnCambiarStatus.setToolTipText("Cambiar Estado");
        btnCambiarStatus.setAlignmentY(0.0F);
        btnCambiarStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnCambiarStatus.setContentAreaFilled(false);
        btnCambiarStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCambiarStatus.setIconTextGap(0);
        btnCambiarStatus.setMargin(new java.awt.Insets(10, 14, 2, 14));
        btnCambiarStatus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons_app/reestablecer_g.png"))); // NOI18N
        btnCambiarStatus.setVerifyInputWhenFocusTarget(false);
        btnCambiarStatus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCambiarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCambiarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(294, 294, 294))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel1);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jPanel3.add(jPanel12, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatosKeyTyped
    if (comboTipoBusqueda.getSelectedIndex()== 1) {
            if(!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()))
            {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
            }
                                                  }
    }//GEN-LAST:event_txtDatosKeyTyped

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void comboTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoBusquedaActionPerformed
    txtDatos.setText("");
    if (comboTipoBusqueda.getSelectedIndex() != 0) {
    txtDatos.setEnabled(true);
                                                   }
    else {
    txtDatos.setEnabled(false);
         }
    }//GEN-LAST:event_comboTipoBusquedaActionPerformed

    private void txtDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatosActionPerformed

    }//GEN-LAST:event_txtDatosActionPerformed

    private void btnListadoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoPersonalActionPerformed
    new viewCatalagoPersonal(null,null,null,this,null,this,true,Dialog.ModalityType.MODELESS).setVisible(true);   
    }//GEN-LAST:event_btnListadoPersonalActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed

    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCambiarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarStatusActionPerformed
        int filaSeleccionada= tableHistorialTramites.getSelectedRow();
        int id_tramite = Integer.parseInt(tableHistorialTramites.getValueAt(filaSeleccionada,6).toString());
        try { 
            new viewCambiarStatus(this,id_tramite,this,true,Dialog.ModalityType.DOCUMENT_MODAL).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(viewHistorialTramites.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCambiarStatusActionPerformed

    private void btnConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar1ActionPerformed
      if (jPanel4.isVisible()==false) {
      jPanel4.setVisible(true);
                                      }
      else if (jPanel4.isVisible()==true) {
      jPanel4.setVisible(false);   
      }
    }//GEN-LAST:event_btnConsultar1ActionPerformed

    private void comboEstatusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboEstatusFocusLost
 
    }//GEN-LAST:event_comboEstatusFocusLost

    private void comboEstatus1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboEstatus1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEstatus1FocusLost

    private void comboTipoTramiteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoTramiteItemStateChanged

    }//GEN-LAST:event_comboTipoTramiteItemStateChanged

    private void btnConsultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultar2ActionPerformed

    private void btnConsultar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultar3ActionPerformed

    private void btnConsultar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultar4ActionPerformed

    private void btnConsultar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultar5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewHistorialTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewHistorialTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewHistorialTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewHistorialTramites.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new viewHistorialTramites(new javax.swing.JFrame(), true,Dialog.ModalityType.DOCUMENT_MODAL).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(viewHistorialTramites.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCambiarStatus;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnConsultar2;
    private javax.swing.JButton btnConsultar3;
    private javax.swing.JButton btnConsultar4;
    private javax.swing.JButton btnConsultar5;
    private javax.swing.JButton btnConsultar6;
    private javax.swing.JButton btnListadoPersonal;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox comboEstatus;
    private javax.swing.JComboBox comboEstatus1;
    private javax.swing.JComboBox comboTipoBusqueda;
    private javax.swing.JComboBox comboTipoTramite;
    private javax.swing.ButtonGroup groupBtnFijoInt;
    private javax.swing.ButtonGroup groupBtnTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableHistorialTramites;
    private javax.swing.JTextField txtDatos;
    private com.toedter.calendar.JDateChooser txtDesde;
    private com.toedter.calendar.JDateChooser txtHasta;
    // End of variables declaration//GEN-END:variables
}
